### PR TITLE
Generated electron-app does not work anymore #166

### LINKED ISSUE #166: Generated electron-app does not work anymore
Currently generating the hello-world app has multiple problems. 

The first issue is
```
'src/browser/hello-world-contribution.ts(14,10): error TS1239: Unable to resolve signature of parameter decorator when called as an expression.\r\n' +
    "  Argument of type 'undefined' is not assignable to parameter of type 'string'.\r\n" +
```
As far as I can see this is fixed on master already (https://github.com/eclipse-theia/generator-theia-extension/issues/164) but not released yet. 

Testing the generation with a local build gives this error then:
```
electron-app: > electron-app@0.0.0 prepare
electron-app: > theia build --mode development
electron-app: Updated dependencies, please run "install" again
electron-app: npm ERR! Lifecycle script `prepare` failed with error: 
electron-app: npm ERR! Error: command failed 
electron-app: npm ERR!   in workspace: electron-app@0.0.0 
electron-app: npm ERR!   at location: /tmp/my-extension/electron-app 
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run prepare
lerna ERR! Updated dependencies, please run "install" again
lerna ERR! npm ERR! Lifecycle script `prepare` failed with error: 
lerna ERR! npm ERR! Error: command failed 
lerna ERR! npm ERR!   in workspace: electron-app@0.0.0 
lerna ERR! npm ERR!   at location: /tmp/my-extension/electron-app 
lerna ERR! 
lerna ERR! 
lerna ERR! > electron-app@0.0.0 prepare
lerna ERR! > theia build --mode development
lerna ERR! 
lerna ERR! 
lerna ERR!     at /tmp/my-extension/node_modules/execa/index.js:236:11
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
```

### PR DESCRIPTION
**Pull request by jfaltermeier**
I think there are two fixes for this. 

The first one would be to simply update the electron version in our template. However I believe with our recent changes, we may more easily update electron in the future. So this might change more often, requiring more regular fixes. 

The second fix would be to remove the electron version from the template completely. 
When we invoke `yarn` for the first time, the theia build will patch the `package.json` and add the supported electron version. This requires a second invocation of `yarn` however, in order to install electron. 
So in the electron case we have to run `yarn` twice, when the electron version is removed from the template. 

Fixes #166

### CODE REVIEW

**Comment by jfaltermeier** [comment]
Both fixes lead to green builds:
1) https://github.com/eclipse-theia/generator-theia-extension/actions/runs/4871969987
2) https://github.com/eclipse-theia/generator-theia-extension/actions/runs/4872257762

Without the fixes the daily build was failing: https://github.com/eclipse-theia/generator-theia-extension/actions

The current PR reflects the changes for #2, however I would just have to revert the last commit to get #1.

File: src/app/index.ts [hunk 1]
```diff
@@ -515,6 +515,11 @@ module.exports = class TheiaExtension extends Base {
                     }
                 });
             } else {
+                if ((this.options as any).electron) {
+                    /* run yarn once. This will update the electron version, which requires a second run */
+                    this.spawnCommandSync('yarn', []);
+                }
```
Comment (vince-fugnitto) [inline src/app/index.ts:521]: @jfaltermeier I don't think this is a viable solution, having to run `yarn` twice for `electron` is not ideal, and when users generate their extensions they get build errors which will only add to the confusion:

- https://github.com/eclipse-theia/generator-theia-extension/actions/runs/4872257762/jobs/8690217178?pr=167#step:5:110

Comment (jfaltermeier) [reply src/app/index.ts:521]: Ok, but if we don't run yarn twice as part of the generator and the electron version available in the template does not match the electron version Theia wants (either because a newer Theia version updates electron or the user specified a different/older theia-version for generation), then the generation will just fail with the same error: https://github.com/eclipse-theia/generator-theia-extension/actions/runs/4866599386/jobs/8678299442#step:5:110 

So this is why I preferred this approach. 

Would it be better if we
a) add the electron version that is currently required to the template,
b) only run yarn twice in the electron case if there was an error, and
c) add some log messages explaining the second run?

Comment (vince-fugnitto) [reply src/app/index.ts:521]: I'd be fine with keeping the behavior as is and making sure that the `electron` version matches the `peerDependencies` version specified by `@theia/electron`. It's the same thing we do for typescript, and node where we match the version required by the framework.

If not I think a solution that does not need a full `yarn` after the fact is best (ex: we get the error, we get duplicated logs for browser-app) as it does not give a good experience. For the most part we have been following the idea that users that generate extensions will use the latest version, not some old version else you might encounter problems.

Comment (jfaltermeier) [reply src/app/index.ts]: :+1: Thanks, I've updated the PR

**Review by JonasHelming — APPROVED** [review]

**Comment by vince-fugnitto** [comment]
@jfaltermeier done :) https://www.npmjs.com/package/generator-theia-extension?activeTab=versions
